name: plant-seg-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pydantic>2
  - h5py
  - zarr
  - requests
  - pyyaml
  - scikit-image
  - tifffile
  - vigra
  - cudnn
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - cuda-version=12.3
  - python-elf
  - pytest
  - pytest-qt
  - pyqt
  - napari
  - python-graphviz
  - bioimageio.core>=0.6.5
  - mkdocs-material
  - mkdocs-autorefs
  - mkdocs-git-revision-date-localized-plugin
  - mkdocs-git-committers-plugin-2
  - mkdocstrings-python
  - pip:
      - markdown-exec
# then `pip install -e .`
