name: plant-seg-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pydantic>2
  - h5py
  - zarr
  - requests
  - pyyaml
  - scikit-image
  - tifffile
  - vigra
  - cudnn
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - cuda-version=12.3
  - python-elf
  - pyqt
  - napari
  - python-graphviz
  - bioimageio.core>=0.6.1
# then `pip install -e .`