package:
  name: plantseg
  version: {{ RELEASE_VERSION }}

source:
  path: ..

build:
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - h5py
    - zarr
    - requests
    - pyyaml
    - scikit-image
    - tifffile
    - vigra
    - pytorch
    - python-elf
    - napari
    - python-graphviz
    - pyqt

test:
  imports:
    - plantseg
    - plantseg.legacy_gui
    - plantseg.segmentation
  requires:
    - pytest
  run:
    - pytest
about:
  home: https://github.com/hci-unihd/plant-seg
  license: MIT
